apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinel-home

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml

labels:
  - pairs:
      app.kubernetes.io/name: sentinel-home
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
    includeTemplates: true

images:
  - name: sentinel-home
    newName: ghcr.io/sentinel-home/sentinel-home
    newTag: latest

configMapGenerator:
  - name: sentinel-home-env
    behavior: create
    literals:
      - NODE_ENV=production
      - PORT=3000
      - OTEL_SERVICE_NAME=sentinel-home
      - LOG_LEVEL=info
