apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sentinel-home
  namespace: sentinel-home
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sentinel-home
      app.kubernetes.io/component: api
