apiVersion: v1
kind: Service
metadata:
  name: sentinel-home
  namespace: sentinel-home
  labels:
    app.kubernetes.io/name: sentinel-home
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sentinel-home
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
